import {installProductionView} from './studio-production-view.js';
import {scenesOf,durationOf,durationLabel,titleOf,formatOf} from './receitas-model.js';
import {businessValues,editBusiness,businessIssues,canRetime,canEditSound,simpleRecipe,editReviewScene,materialChoices,toggleMaterial} from './gerador-guided-model.js';

export function installGuidedGenerator(ctx){
  const $=id=>document.getElementById(id),node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!=null)n.textContent=text;return n;};
  const button=(text,fn,cls='')=>{const b=node('button',cls,text);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(showError);return b;};
  const root=node('main','guided-root');root.id='guided-root';
  root.innerHTML=`
  <div class="guide-top"><div><span class="guide-kicker">DO SEU JEITO</span><h1>Vamos criar um vídeo.</h1></div><button id="guide-history" class="quiet">Meus vídeos</button></div>
  <nav class="guide-steps" aria-label="Passos para criar o vídeo"><button data-guide-step="0"><span>1</span> Ideia</button><button data-guide-step="1"><span>2</span> Aparência</button><button data-guide-step="2"><span>3</span> Voz e música</button><button data-guide-step="3"><span>4</span> Revisar e gerar</button></nav>
  <div class="guide-workspace"><section class="guide-form-area"><div id="guide-error" role="alert" hidden></div>
  <section data-guide-page="0"><div class="guide-page-title"><span>PASSO 1 DE 4</span><h2>O que vamos contar?</h2><p>Comece com uma ideia ou aproveite uma receita que você já tem.</p></div>
  <div class="guide-start-options"><button id="guide-new"><b>＋ Criar um vídeo novo</b><span>Uma base simples, pronta para sua ideia.</span></button><button id="guide-reuse"><b>▤ Usar uma receita</b><span>Escolha uma estrutura e faça sua versão.</span></button></div>
  <div class="guide-base"><span id="guide-base-name"></span><button id="guide-change-base">Trocar base</button></div>
  <label class="guide-field">Nome do vídeo<input data-business="name" id="guide-name" maxlength="140" placeholder="Ex.: Meu café favorito"></label>
  <label class="guide-field">Qual é o tema?<textarea data-business="theme" id="guide-theme" rows="2" placeholder="Ex.: um café artesanal, preparado com calma, para começar bem o dia"></textarea><small>Conte sobre o produto, a história ou a ideia que deve aparecer.</small></label>
  <label class="guide-field">Qual mensagem precisa ficar?<input data-business="message" id="guide-message" maxlength="2000" placeholder="Ex.: pequenos cuidados transformam a rotina"></label>
  <div class="guide-two"><label class="guide-field">Tempo total desejado<div class="guide-number"><input data-business="duration" id="guide-duration" type="number" min="4" max="120" step="1"><span>segundos</span></div><small id="guide-duration-help"></small></label><label class="guide-field">Para quem é o vídeo?<input data-business="audience" id="guide-audience" placeholder="Ex.: clientes, crianças, minha equipe"></label></div>
  <fieldset class="guide-choice-field"><legend>Onde você vai assistir?</legend><div class="guide-ratios"><button data-aspect="9:16"><i class="ratio-portrait"></i><b>Em pé</b><span>Celular · 9:16</span></button><button data-aspect="16:9"><i class="ratio-landscape"></i><b>Deitado</b><span>TV e YouTube · 16:9</span></button><button data-aspect="1:1"><i class="ratio-square"></i><b>Quadrado</b><span>Publicações · 1:1</span></button></div></fieldset>
  </section>
  <section data-guide-page="1" hidden><div class="guide-page-title"><span>PASSO 2 DE 4</span><h2>Como ele deve parecer?</h2><p>Escolha a aparência e o ritmo. O que já funciona na base pode continuar.</p></div>
  <label class="guide-field">Estilo visual<select data-business="style" id="guide-style"><option value="">Manter a direção da receita</option></select><small id="guide-style-help">A aparência das imagens: realista, desenho, animação e outras opções.</small></label>
  <fieldset class="guide-choice-field"><legend>Ritmo do vídeo <span>Dinâmica</span></legend><div class="guide-choice-row"><button data-dynamics="keep">Da receita</button><button data-dynamics="calm">Calmo</button><button data-dynamics="balanced">Equilibrado</button><button data-dynamics="energetic">Animado</button></div><p class="guide-help">Controla a intenção dos movimentos e das mudanças visuais.</p></fieldset>
  <label class="guide-field">Quer imagens de apoio? <span>Inserts</span><select data-business="inserts" id="guide-inserts"><option value="keep">Manter como está na base</option><option value="details">Intercalar closes e detalhes</option><option value="none">Manter cada cena contínua</option></select><small>Inserts são pequenos trechos de detalhe que ajudam a contar a história.</small></label>
  <div class="guide-section-title"><h3>Logo e referências</h3><p>Materiais desta receita que ajudam a manter uma marca, pessoa ou imagem.</p></div><div id="guide-materials"></div><button id="guide-material-base" class="guide-text-button">Escolher uma base com outros materiais →</button>
  <details class="guide-extra"><summary>Como o vídeo termina? <span>Arremate</span></summary><label class="guide-field">Tipo de final<select data-business="ending" id="guide-ending"><option value="keep">Manter o final da receita</option><option value="clean">Corte limpo ao terminar</option><option value="hold">Deixar a última imagem respirar</option></select></label><label class="guide-field" id="guide-hold-field" hidden>Tempo para a imagem final<div class="guide-number"><input data-business="hold" id="guide-hold" type="number" min="1" max="15"><span>segundos</span></div><small>Esse tempo faz parte da última cena, dentro do total.</small></label><label class="guide-field">Mensagem final ou convite<input data-business="cta" id="guide-cta" maxlength="240" placeholder="Ex.: Conheça nossa coleção"><small>Aparece no encerramento. Você confere o texto no próximo passo.</small></label></details>
  </section>
  <section data-guide-page="2" hidden><div class="guide-page-title"><span>PASSO 3 DE 4</span><h2>O que vamos ouvir?</h2><p>Voz conta a história. Música cria o clima. Você pode usar as duas ou nenhuma.</p></div>
  <div id="guide-sound-locked" class="guide-note" hidden></div>
  <div class="guide-option-box"><label class="guide-switch"><span><b>Quero uma voz contando a história</b><small>Locução</small></span><input data-business="narration" id="guide-narration" type="checkbox"></label><div id="guide-voice-fields" hidden><label class="guide-field">O que a voz vai falar?<textarea data-business="speech" id="guide-speech" rows="4" placeholder="Escreva aqui as palavras que devem ser faladas."></textarea><small id="guide-speech-help"></small></label><div class="guide-two"><label class="guide-field">Voz<select data-business="voice" id="guide-voice"></select></label><label class="guide-field">Jeito de falar<input data-business="voiceDirection" id="guide-voiceDirection" placeholder="Ex.: acolhedor, alegre, com calma"></label></div><label class="guide-field">Projeto de voz no Google Vids<input data-business="voiceProject" id="guide-voiceProject" type="url" placeholder="Cole o link do projeto de voz"><small>O Studio usa esse projeto para criar a locução. <a href="https://docs.google.com/videos/" target="_blank" rel="noopener">Abrir Google Vids ↗</a></small></label></div></div>
  <div class="guide-option-box"><label class="guide-switch"><span><b>Quero música de fundo</b><small>Trilha sonora</small></span><input data-business="music" id="guide-music" type="checkbox"></label><div id="guide-music-fields" hidden><label class="guide-field">Qual é o clima da música?<textarea data-business="musicIntent" id="guide-musicIntent" rows="2" placeholder="Ex.: instrumental leve, alegre, com violão"></textarea><small>A trilha acompanha o vídeo e fica abaixo da voz.</small></label><p class="guide-help">O final segue a receita, sem acrescentar fade-out automático.</p></div></div>
  </section>
  <section data-guide-page="3" hidden><div class="guide-page-title"><span>PASSO 4 DE 4</span><h2>Está do jeito que você imaginou?</h2><p>Confira as cenas e o som. Depois, é só gerar.</p></div><div id="guide-review-summary"></div><div id="guide-issues"></div><div class="guide-section-title"><h3>Seu vídeo, cena por cena</h3><p>A duração de cada trecho compõe o tempo total. Abra uma cena para ajustar os detalhes.</p></div><div id="guide-scenes"></div><details class="guide-extra"><summary>Opções de entrega</summary><label class="guide-switch"><span><b>Seguir até o vídeo pronto</b><small>Se desligado, a receita pode parar para revisar a prévia.</small></span><input data-business="automatic" id="guide-automatic" type="checkbox"></label><button id="guide-save" class="guide-text-button">Salvar esta versão na biblioteca</button></details><p class="guide-help">Ao gerar, o Studio prepara esta versão e inicia a produção. As receitas e os vídeos originais ficam preservados.</p></section>
  <section id="guide-progress" hidden><div class="guide-page-title"><span>SEU VÍDEO</span><h2 id="guide-progress-title">Preparando seu vídeo…</h2><p id="guide-progress-message">Você pode acompanhar cada etapa aqui.</p></div><div id="guide-progress-steps"></div><div id="guide-progress-scenes"></div><div id="guide-result"></div><div id="guide-progress-actions"></div></section>
  </section>
  <aside class="guide-summary" aria-label="Resumo do vídeo"><span class="guide-kicker">SEU PEDIDO</span><div id="guide-format-card" class="guide-format-card"><div><span id="guide-summary-theme"></span><small id="guide-summary-format"></small></div></div><h3 id="guide-summary-name"></h3><dl id="guide-summary-values"></dl><p class="guide-help">Este é o resumo do pedido. O vídeo aparece aqui quando estiver pronto.</p><button id="guide-preview-base" class="guide-text-button" hidden>Assistir ao exemplo da receita</button></aside></div>
  <footer class="guide-footer"><button id="guide-back" class="quiet">← Voltar</button><span id="guide-footer-note">Você pode mudar suas escolhas antes de gerar.</span><button id="guide-next" class="primary">Continuar: aparência →</button></footer>`;
  document.body.append(root);document.body.classList.add('guided-mode');root.inert=true;root.dataset.loading='true';root.setAttribute('aria-busy','true');const loader=node('p','guide-loading','Abrindo seu Studio…');root.prepend(loader);
  const firstPage=root.querySelector('[data-guide-page="0"]'),extras=node('details','guide-extra');extras.append(node('summary','','Mais detalhes · nome, mensagem e público'));
  for(const id of ['guide-name','guide-message','guide-audience'])extras.append($(id).closest('label'));
  firstPage.querySelector('.guide-two').append(firstPage.querySelector('.guide-choice-field'));firstPage.append(extras);
  const useMusic=button('Usar a descrição musical desta receita',()=>commit({music:true,musicIntent:ctx.state().draft.trilha.intencao}),'guide-text-button');useMusic.id='guide-use-music-brief';useMusic.hidden=true;$('guide-music-fields').prepend(useMusic);
  const mode=button('Editor avançado',()=>setAdvanced(document.body.classList.contains('guided-mode')),'guide-mode-button');mode.id='guide-mode';document.querySelector('.studio-header').append(mode);
  let step=0,compatibility=null,lastSource='',lastDraft='',configured=false,progressJob=null,flow=null,flowError='',uiBusy=false;
  const pageTitles=['Continuar: aparência →','Continuar: voz e música →','Revisar meu vídeo →','Gerar vídeo'];
  function setAdvanced(enabled){if(uiBusy)return;document.body.classList.toggle('guided-mode',!enabled);const url=new URL(location.href);if(enabled)url.searchParams.set('advanced','1');else url.searchParams.delete('advanced');history.replaceState(null,'',url);mode.textContent=enabled?'← Criação guiada':'Editor avançado';if(enabled){document.body.classList.remove('focus-mode');$('view-story').hidden=false;document.querySelector('[data-view=story]').click();}else{$('story-real')?.pause();$('editor-frame').contentDocument?.querySelectorAll('video').forEach(v=>v.pause());update();}}
  function showError(error){$('guide-error').textContent=error?.message||String(error);$('guide-error').hidden=false;$('guide-error').scrollIntoView({block:'nearest'});}
  function clearError(){$('guide-error').hidden=true;}
  function commit(patch){try{clearError();ctx.replace(editBusiness(ctx.state().draft,patch));return true;}catch(e){showError(e);update(true);return false;}}
  for(const field of root.querySelectorAll('[data-business]'))field.onchange=()=>{const key=field.dataset.business,value=field.type==='checkbox'?field.checked:field.type==='number'?Number(field.value):field.value;commit({[key]:value});};
  root.querySelectorAll('[data-aspect]').forEach(b=>b.onclick=()=>commit({aspect:b.dataset.aspect}));
  root.querySelectorAll('[data-dynamics]').forEach(b=>b.onclick=()=>commit({dynamics:b.dataset.dynamics}));
  function showStep(next){if(uiBusy)return;$('guide-progress').querySelectorAll('video').forEach(v=>v.pause());document.body.classList.remove('production-mode');const url=new URL(location.href);url.searchParams.delete('job');history.replaceState(null,'',url);document.title='Criar vídeo · Studio';if(progressJob?.id)localStorage.removeItem('studio-generator-active-job');clearError();step=Math.max(0,Math.min(3,next));progressJob=null;flowError='';root.querySelectorAll('[data-guide-page]').forEach(n=>n.hidden=Number(n.dataset.guidePage)!==step);$('guide-progress').hidden=true;root.querySelectorAll('[data-guide-step]').forEach(n=>{n.setAttribute('aria-current',Number(n.dataset.guideStep)===step?'step':'false');n.classList.toggle('passed',Number(n.dataset.guideStep)<step);});$('guide-back').hidden=step===0;$('guide-next').textContent=pageTitles[step];$('guide-next').hidden=false;$('guide-footer-note').textContent=step===3?'Uma ação para preparar e começar.':'Você pode mudar suas escolhas antes de gerar.';root.querySelector('.guide-form-area').scrollTop=0;update();}
  root.querySelectorAll('[data-guide-step]').forEach(b=>b.onclick=()=>showStep(Number(b.dataset.guideStep)));
  $('guide-back').onclick=()=>showStep(step-1);
  $('guide-history').onclick=()=>{location.href='/';};
  $('guide-save').onclick=()=>$('save-version').click();
  $('guide-next').onclick=async()=>{if(uiBusy)return;clearError();const issues=businessIssues(ctx.state().draft).filter(i=>step===3||i.step===step);if(issues.length)return jumpIssue(issues[0]);if(step<3)return showStep(step+1);if(compatibility?.level!=='ready')return showError('Ainda falta um ajuste. Veja os avisos acima e confira a base escolhida.');await generate();};
  function jumpIssue(issue){showStep(issue.step);showError(issue.text);$('guide-'+issue.field)?.focus();}
  const chooser=node('dialog','guide-chooser');chooser.id='guide-chooser';chooser.innerHTML='<div class="panel-heading"><div><h2>Escolha sua base</h2><p>A estrutura vem pronta. O conteúdo pode ser seu.</p></div><button id="guide-close-chooser" aria-label="Fechar escolha de base">×</button></div><input id="guide-search" type="search" placeholder="Buscar uma receita…" aria-label="Buscar uma base"><div class="guide-filters"><button data-guide-filter="all">Todas</button><button data-guide-filter="ready">Prontas para gerar</button><button data-guide-filter="voice">Com voz</button><button data-guide-filter="music">Com música</button></div><div id="guide-recipe-list"></div>';
  document.body.append(chooser);let filter='all';
  const renderChoices=()=>{const query=$('guide-search').value.toLocaleLowerCase(),list=ctx.library().filter(r=>(r.title+' '+r.family).toLocaleLowerCase().includes(query)&&(filter==='all'||filter==='ready'&&r.compatibility?.level==='ready'||filter==='voice'&&r.narration||filter==='music'&&r.music));$('guide-recipe-list').replaceChildren(...list.map(r=>{const b=button('',async()=>{chooser.close();await ctx.openRecipe(r.file);showStep(0);});b.className='guide-recipe';b.append(node('b','',r.title),node('span','',`${r.sceneCount} cenas · ${durationLabel(r.duration)} · ${r.aspect||'Formato da base'}`),node('small',r.compatibility?.level==='ready'?'ready':'',r.compatibility?.level==='ready'?'Pronta para personalizar':r.compatibility?.label||'Conferir estrutura'));return b;}));if(!list.length)$('guide-recipe-list').append(node('p','guide-help','Nenhuma base encontrada com esses filtros.'));chooser.querySelectorAll('[data-guide-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.guideFilter===filter)));};
  const choose=()=>{renderChoices();chooser.showModal();$('guide-search').focus();};
  $('guide-reuse').onclick=$('guide-change-base').onclick=$('guide-material-base').onclick=choose;
  $('guide-close-chooser').onclick=()=>chooser.close();$('guide-search').oninput=renderChoices;chooser.querySelectorAll('[data-guide-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.guideFilter;renderChoices();});
  $('guide-new').onclick=async()=>{try{if(!await ctx.openRecipe('studio-produto.receita.json'))return;commit({mode:'create',name:'Meu novo vídeo',theme:'',message:'',automatic:true});showStep(0);$('guide-theme').focus();}catch(e){showError(e);}};
  const example=node('dialog','guide-example');example.innerHTML='<div class="panel-heading"><h2>Vídeo da receita de origem</h2><button aria-label="Fechar exemplo">×</button></div><video controls playsinline preload="metadata"></video><p>Este exemplo é da base escolhida. Suas alterações ainda não foram geradas.</p>';document.body.append(example);example.querySelector('button').onclick=()=>example.close();example.onclose=()=>example.querySelector('video').pause();$('guide-preview-base').onclick=()=>{const src=$('story-real')?.getAttribute('src');if(!src)return;example.querySelector('video').src=src;example.showModal();};
  function renderMaterials(){const {source,draft}=ctx.state(),choices=materialChoices(source.document,draft),target=$('guide-materials');target.replaceChildren();for(const [kind,title,help] of [['logo','Logo','Marca que aparece no vídeo.'],['image','Imagem de referência','Ajuda a manter a pessoa ou a aparência.'],['video','Vídeo de referência','Material de vídeo já ligado à base.']]){
    const group=node('div','guide-material-group');group.append(node('b','',title),node('small','',help));const matches=choices.filter(c=>c.kind===kind);
    if(!matches.length)group.append(node('span','guide-material-empty','Nenhum nesta base'));
    for(const choice of matches){const label=node('label','guide-material-item'),c=node('input');c.type='checkbox';c.checked=choice.enabled;c.disabled=!choice.editable;c.setAttribute('aria-label','Usar '+choice.name);c.onchange=()=>{try{ctx.replace(toggleMaterial(ctx.state().draft,ctx.state().source.document,choice.key,c.checked));}catch(e){showError(e);}};label.append(c,node('span','',choice.name+(choice.scene!=null?' · cena '+(choice.scene+1):'')));if(!choice.editable)label.title='Vínculo próprio da receita. Disponível no editor avançado.';group.append(label);}target.append(group);
  }target.append(node('p','guide-help','As escolhas acima usam materiais já vinculados à base. Novos arquivos precisam ser vinculados à receita antes de gerar.'));}
  function renderScenes(){const {draft}=ctx.state(),target=$('guide-scenes'),open=[...target.querySelectorAll('details[open]')].map(n=>n.dataset.index);target.replaceChildren();scenesOf(draft).forEach((s,i,all)=>{
    const raw=s.path.reduce((v,k)=>v?.[k],draft),block=draft.audio?.narration?.blocks?.find(b=>b.id===s.id||b.sceneId===s.id),box=node('article','guide-scene');const summary=node('div','guide-scene-heading'),name=/^cena[-_]\d+$/.test(s.name)?i===0?'Abertura':i===all.length-1?'Encerramento':'Desenvolvimento':s.name.replaceAll('-',' ');summary.append(node('span','guide-scene-number',String(i+1).padStart(2,'0')),node('b','',name),node('span','guide-scene-time',durationLabel(s.duration)));box.append(summary);
    const evidence=node('div','guide-scene-facts');evidence.append(node('span','',raw.references?.length?'Referência: '+raw.references.map(r=>String(r.relPath).split(/[\\/]/).at(-1)).join(', '):'Imagem: direção da cena'),node('span','',block?'Voz: '+block.text:draft.audio?.narration?'Voz da locução principal':'Sem locução separada'),node('span','',raw.onScreenText?'Na tela: '+raw.onScreenText:'Sem texto na tela'),node('span','',draft.audio?.music||draft.music?'Trilha prevista':'Sem trilha'));box.append(evidence);
    const details=node('details');details.dataset.index=i;details.open=open.includes(String(i));details.append(node('summary','','Editar esta cena'));
    for(const [key,label,value,type,enabled] of [['duration','Duração desta cena',s.duration,'number',canRetime(draft)],['prompt','O que aparece e acontece?',s.prompt,'textarea',s.path[0]!=='identidade'],['text','Texto que aparece na tela',raw.onScreenText||'','input',simpleRecipe(draft)],...(block?[['speech','Fala desta cena',block.text,'textarea',simpleRecipe(draft)]]:[])]){const l=node('label','guide-field',label),input=node(type==='textarea'?'textarea':'input');if(type==='textarea')input.rows=4;else input.type=type==='number'?'number':'text';input.value=value??'';input.disabled=!enabled;input.setAttribute('aria-label',label+' '+(i+1));input.onchange=()=>{try{ctx.replace(editReviewScene(ctx.state().draft,i,{[key]:input.value}));}catch(e){showError(e);}};l.append(input);details.append(l);}box.append(details);target.append(box);
  });}
  function renderReview(){const {draft}=ctx.state(),v=businessValues(draft);$('guide-review-summary').textContent=`${durationLabel(v.duration)} no total · ${scenesOf(draft).length} cenas · ${v.aspect} · ${v.narration?'com locução':'sem locução separada'} · ${v.music?'com música':'sem música'}`;
    const issues=businessIssues(draft);$('guide-issues').replaceChildren(...issues.map(i=>button(i.text+' →',()=>jumpIssue(i),'guide-issue')));
    if(compatibility&&compatibility.level!=='ready')for(const reason of compatibility.reasons)$('guide-issues').append(node('p','guide-note',reason));
    if(!issues.length&&compatibility?.level==='ready')$('guide-issues').append(node('p','guide-ready','✓ As escolhas estão prontas para a preparação.'));
    renderScenes();
  }
  function update(force=false){const {source,draft}=ctx.state();if(!source||!draft)return;
    if(!configured&&ctx.config()){configured=true;$('guide-style').append(...ctx.config().styles.map(s=>{const o=node('option','',s.name);o.value=s.id;return o;}));$('guide-voice').replaceChildren(...(ctx.config().voices?.voices||[]).map(v=>{const o=node('option','',v.name);o.value=v.name;return o;}));}
    const fingerprint=JSON.stringify(draft),changed=lastDraft!==fingerprint;
    if(changed)compatibility=null;
    if(lastSource!==source.file){lastSource=source.file;compatibility=null;progressJob=null;flowError='';}
    const v=businessValues(draft);for(const field of root.querySelectorAll('[data-business]')){if(field===document.activeElement&&!force)continue;const value=v[field.dataset.business];if(field.type==='checkbox')field.checked=!!value;else field.value=value??'';}
    $('guide-base-name').textContent='Base: '+titleOf(source.document);
    $('guide-duration').disabled=!canRetime(draft);$('guide-duration').min=scenesOf(draft).length*4;$('guide-duration').max=simpleRecipe(draft)?120:86400;
    $('guide-duration-help').textContent=canRetime(draft)?`O total é dividido entre ${scenesOf(draft).length} cenas. Cada cena tem pelo menos 4 segundos.`:'Esta base tem tempos vinculados. O total é preservado; detalhes ficam no editor avançado.';
    $('guide-style').disabled=!simpleRecipe(draft);$('guide-style-help').textContent=simpleRecipe(draft)?'Escolha a aparência das imagens.':'Esta receita define o estilo dentro de cada cena. Você pode mudar a direção na revisão.';
    $('guide-automatic').disabled=!simpleRecipe(draft);
    root.querySelectorAll('[data-aspect]').forEach(b=>{b.disabled=simpleRecipe(draft)&&b.dataset.aspect==='1:1';b.hidden=b.disabled;b.setAttribute('aria-pressed',String(b.dataset.aspect===v.aspect));});
    root.querySelectorAll('[data-dynamics]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dynamics===v.dynamics)));
    $('guide-hold-field').hidden=v.ending!=='hold';$('guide-voice-fields').hidden=!v.narration;$('guide-music-fields').hidden=!v.music;
    const sound=canEditSound(draft),blocks=draft.audio?.narration?.blocks||[];$('guide-sound-locked').hidden=sound;$('guide-sound-locked').textContent='Esta base tem som sincronizado com as cenas. As escolhas são preservadas; confira os textos e vínculos na revisão ou no editor avançado.';
    for(const key of ['narration','voice','speech','voiceProject','voiceDirection','music','musicIntent'])$('guide-'+key).disabled=!sound||key==='speech'&&blocks.length>1;
    $('guide-use-music-brief').hidden=!draft.trilha?.intencao||!!draft.audio?.musicIntent;
    $('guide-speech-help').textContent=blocks.length>1?'Esta locução é dividida por cena. Edite cada fala na revisão.':'Escreva apenas o que deve ser falado. O texto na tela é uma escolha separada.';
    $('guide-summary-name').textContent=v.name;$('guide-summary-theme').textContent=v.theme||'Sua ideia, em vídeo';$('guide-summary-format').textContent=v.aspect+' · '+durationLabel(v.duration);$('guide-format-card').dataset.aspect=v.aspect;
    $('guide-summary-values').replaceChildren(...[['Duração total',durationLabel(v.duration)],['Cenas',scenesOf(draft).length],['Voz',v.narration?'Sim':'Não separada'],['Música',v.music?'Sim':'Não'],['Estilo',ctx.config()?.styles.find(s=>s.id===v.style)?.name||'Da receita']].flatMap(([k,value])=>[node('dt','',k),node('dd','',String(value))]));
    $('guide-preview-base').hidden=!$('story-real')?.getAttribute('src');
    if(changed||force){lastDraft=fingerprint;renderMaterials();renderReview();}
    $('guide-next').disabled=uiBusy||step===3&&(businessIssues(draft).length>0||compatibility?.level!=='ready');
    if(!progressJob&&!uiBusy){root.querySelectorAll('[data-guide-page]').forEach(n=>n.hidden=Number(n.dataset.guidePage)!==step);$('guide-progress').hidden=true;}
  }
  const productionView=installProductionView($('guide-progress'),{
    error:e=>showError(e), editor:job=>{$('guide-progress').querySelectorAll('video').forEach(v=>v.pause());setAdvanced(true);ctx.openEditor(job.recipeFile);},
    details:()=>$('jobs-toggle').click(),
    choices:()=>{flow=null;uiBusy=false;mode.disabled=false;showStep(0);},
    fix:async(job,issue)=>{uiBusy=false;mode.disabled=false;flow=null;if(job.recipeFile&&job.recipeFile!==ctx.state().source?.file&&!await ctx.openRecipe(job.recipeFile))return;showStep(issue.step??3);if(issue.field){showError(issue.text);$('guide-'+issue.field)?.focus();}},
    execute:async(job,operation)=>{if(uiBusy)return;uiBusy=true;mode.disabled=true;flowError='';try{const accepted=operation==='run'?await ctx.run(job):await ctx.api('/api/gerador/resume',{id:job.id,recipeHash:job.recipeHash});progress(accepted);await ctx.refresh();}catch(e){flowError=e.message;progress({...job,status:'interrupted'});}finally{uiBusy=['planning','running'].includes(progressJob?.status);mode.disabled=uiBusy;}}
  });
  function progress(job){progressJob=job;root.querySelectorAll('[data-guide-page]').forEach(n=>n.hidden=true);$('guide-progress').hidden=false;$('guide-back').hidden=true;$('guide-next').hidden=true;
    if(job.id){const url=new URL(location.href);url.searchParams.set('job',job.id);history.replaceState(null,'',url);}
    productionView.update(job,{autoStart:!!flow,error:flowError});
  }
  async function generate(){
    uiBusy=true;mode.disabled=true;flowError='';flow={id:null,submitted:false};update();progress({status:'planning',name:titleOf(ctx.state().draft)});
    try{const job=await ctx.prepare({autoStart:true});flow.id=job.id;flow.submitted=!!job.autoStartRequested;localStorage.setItem('studio-generator-active-job',JSON.stringify({id:job.id,source:ctx.state().source.file}));progress(job);await ctx.refresh();}catch(e){flow=null;uiBusy=false;mode.disabled=false;flowError=e.message;progress({status:'attention',name:titleOf(ctx.state().draft),message:e.message});}
  }
  async function jobs(items){
    let remembered;try{remembered=JSON.parse(localStorage.getItem('studio-generator-active-job'));}catch{}
    const requested=new URLSearchParams(location.search).get('job');
    const job=flow?.id?items.find(j=>j.id===flow.id):progressJob?.id?items.find(j=>j.id===progressJob.id):requested?items.find(j=>j.id===requested):remembered?.source===ctx.state().source?.file?items.find(j=>j.id===remembered.id):null;if(!job)return;
    if(['planning','running'].includes(job.status)){uiBusy=true;mode.disabled=true;}
    if(job.status==='ready'&&!flow){uiBusy=false;mode.disabled=false;}
    if(['running','complete'].includes(job.status))flowError='';
    if(flow&&job.status==='ready'&&!flow.submitted){flow.submitted=true;try{const accepted=await ctx.run(job);if(!['running','complete'].includes(accepted.status)){flow=null;uiBusy=false;mode.disabled=false;}progress(accepted);}catch(e){flowError=e.message;flow=null;uiBusy=false;mode.disabled=false;progress({...job,status:'interrupted'});}return;}
    if(['attention','interrupted','paused','complete'].includes(job.status)){flow=null;uiBusy=false;mode.disabled=false;}
    progress(job);
  }
  const initialJob=new URLSearchParams(location.search).get('job');showStep(0);if(initialJob){const url=new URL(location.href);url.searchParams.set('job',initialJob);history.replaceState(null,'',url);}
  if(new URLSearchParams(location.search).get('advanced')==='1')setAdvanced(true);
  return {update,jobs,ready(){root.inert=false;root.setAttribute('aria-busy','false');if(ctx.state().source){root.dataset.loading='false';loader.hidden=true;}else{root.dataset.loading='error';loader.textContent='Não foi possível abrir o Studio. Atualize a página para tentar novamente.';}},connection:productionView.connection,choose,watch:progress,isWorking:()=>!!flow||uiBusy,compatibility(result){compatibility=result;renderReview();update();},advanced:setAdvanced,async follow(job){if(uiBusy)return ctx.notify('Uma produção já está em andamento nesta tela.');if(job.recipeFile&&!await ctx.openRecipe(job.recipeFile))return;localStorage.setItem('studio-generator-active-job',JSON.stringify({id:job.id,source:ctx.state().source.file}));$('close-jobs').click();setAdvanced(false);progress(job);uiBusy=['planning','running'].includes(job.status);mode.disabled=uiBusy;}};
}
