import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, symlink, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { discoverEditorCollections } from '../app/editor/editor-collections.mjs';

test('empty installation has no borrowed production; collection uses its own audio and measured clips', async t => {
  const temporary = await mkdtemp(path.join(os.tmpdir(), 'editor-collections-'));
  t.after(async () => { assert.equal(path.dirname(temporary), os.tmpdir()); await rm(temporary, { recursive: true, force: true }); });
  const core = path.join(temporary, 'core');
  await mkdir(core);
  assert.deepEqual(await discoverEditorCollections(core), []);
  const folder = path.join(core, 'outputs', 'meu-estudo');
  for (const name of ['videos-soltos', 'videos-unidos', 'audios-soltos']) await mkdir(path.join(folder, name), { recursive: true });
  for (const name of ['clip.mp4', 'video-unido-raw.mp4']) await writeFile(path.join(folder, 'videos-soltos', name), 'synthetic');
  for (const name of ['voz.wav', 'trilha.wav']) await writeFile(path.join(folder, 'audios-soltos', name), 'synthetic');
  const probe = async () => ({ duration: 3.75 });
  const [project] = await discoverEditorCollections(core, { probe });
  assert.equal(project.scenes[0].duration, 3.75);
  assert.equal(project.scenes.length, 1);
  assert.equal(project.audioVoice, 'outputs/meu-estudo/audios-soltos/voz.wav');
  assert.equal(project.audioMusic, 'outputs/meu-estudo/audios-soltos/trilha.wav');
  assert.deepEqual(project.whisperWords, []);
  assert.equal(project.masterRel, null);
  await writeFile(path.join(folder, 'videos-unidos', 'um.mp4'), 'synthetic');
  await writeFile(path.join(folder, 'videos-unidos', 'dois.mp4'), 'synthetic');
  assert.equal((await discoverEditorCollections(core, { probe }))[0].masterRel, null, 'multiple masters require explicit selection');
  await rm(path.join(folder, 'audios-soltos'), { recursive: true });
  const elsewhere = path.join(temporary, 'other-audio');
  await mkdir(elsewhere);
  await writeFile(path.join(elsewhere, 'voz.wav'), 'not collection audio');
  await symlink(elsewhere, path.join(folder, 'audios-soltos'), process.platform === 'win32' ? 'junction' : 'dir');
  const [withoutAudio] = await discoverEditorCollections(core, { probe: async () => { throw new Error('no probe'); } });
  assert.equal(withoutAudio.audioVoice, null);
  assert.equal(withoutAudio.audioMusic, null);
  assert.equal(withoutAudio.scenes[0].duration, null, 'unmeasured duration is not fabricated');
  const server = await readFile(new URL('../app/editor/server.mjs', import.meta.url), 'utf8');
  assert.doesNotMatch(server, /5-comerciais-apresentacao|5-colecoes-flat|10-colecoes-flat|locução Jett/);
});
